---
- hosts: webserver
  tasks:
  - name: Install nginx
    apt: name=nginx state=latest
  - name: Copy nginx additional config
    copy:
      src: jenkins
      dest: /etc/nginx/sites-enabled/jenkins
      owner: root
      group: root
      mode: 0644
  - name: Restart nginx
    service:
      name: nginx
      state: restarted

- hosts: appserver
  vars:
    jenkins_key: https://pkg.jenkins.io/debian/jenkins.io.key
    jenkins_url: http://pkg.jenkins.io/debian-stable
  tasks:
  - name: Install Java
    apt:
      name: openjdk-8-jdk
      state: latest
      install_recommends: no
      update_cache: yes
  - name: Import the GPG keys of the Jenkins repository
    shell: wget -q -O - {{ jenkins_key }} | apt-key add -
    args:
      warn: false
  - name: Add the Jenkins Debian repository
    apt_repository:
      repo: deb {{ jenkins_url }} binary/
      filename: 'jenkins'
  - name: Install Jenkins
    apt:
      name: jenkins
      state: latest
      update_cache: yes
  - name: Ensure Jenkins is started
    service:
      name: jenkins
      state: started
...
